<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-C3O2LMD" ignored="0" name="Default test" tests="2" failures="0" timestamp="22 Apr 2021 09:30:38 GMT" time="9.324" errors="0">
  <testcase name="@BeforeTest openUrl" time="9.028" classname="com.cjc.mt.tests.Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [http://demo.guru99.com/test/newtours/register] but found [http://demo.guru99.com/test/newtours/register.php]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.cjc.mt.tests.Test.openUrl(Test.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest openUrl -->
  <testcase name="@BeforeClass maximize" time="0.0" classname="com.cjc.mt.tests.Test">
    <skipped/>
  </testcase> <!-- @BeforeClass maximize -->
  <testcase name="@BeforeMethod createCookies" time="0.0" classname="com.cjc.mt.tests.Test">
    <skipped/>
  </testcase> <!-- @BeforeMethod createCookies -->
  <testcase name="@BeforeMethod createCookies" time="0.0" classname="com.cjc.mt.tests.Test">
    <skipped/>
  </testcase> <!-- @BeforeMethod createCookies -->
  <testcase name="registerTest" time="0.0" classname="com.cjc.mt.tests.Test">
    <skipped/>
  </testcase> <!-- registerTest -->
  <testcase name="loginTest" time="0.0" classname="com.cjc.mt.tests.Test">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
